# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

use_frameworks!

target 'EGFloatingTextField' do
pod 'PureLayout', '~> 2.0'

end

target 'EGFloatingTextFieldTests' do

end

