source 'https://github.com/CocoaPods/Specs.git'
workspace 'EGFloatingTextField.xcworkspace'
platform :ios, '8.0'
use_frameworks!

##
## Integrate pods with targets
##

target 'EGFloatingTextField' do
    project 'EGFloatingTextField.xcodeproj'
    pod 'PureLayout'
    target 'Example' do
    end
    target 'EGFloatingTextFieldTests' do
    end
end




post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['VALID_ARCHS'] = 'armv7 arm64 armv7s x86_64'
        end
    end
end
